version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    networks:
      - wordpress_network
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - C:\Users\user\Documents\Git-Comp-tanceInfo-CarteMentale\Carte-Compétance-Obsédian\Docker\wordpress-docker\Volume2:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "8080:80"
    networks:
      - wordpress_network
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - C:\Users\user\Documents\Git-Comp-tanceInfo-CarteMentale\Carte-Compétance-Obsédian\Docker\wordpress-docker\Volume1:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - wordpress_network
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=wordpress_user
      - PMA_PASSWORD=wordpress_password

networks:
  wordpress_network:
